### ISSUE TITLE
同じ時刻がふたつ出力されることがある

### ISSUE THREAD

**Issue by pankona** [sassy/KeiseiBusTime#4]
2014.08.14 Fri 20:24 に実行したところ、

```
$ KeiseiBusTime
20:26
20:26
20:29
```

という出力結果を得ました。
おそらく期待結果ではないと思われますので、一応、ご報告致します。

**Comment by sassy** [comment]
@pankona 
これって実は時刻表では期待通りなんですよ。
上記は20:26分に2台バスが来ると言う意味で、時刻表にも26が二つ表記されています。
利用者側としては一つにまとめた方がいいですかね。。。

**Comment by pankona** [comment]
@sassy 
その可能性は頭をよぎりましたが、、、まさか同着があるとは知らなんだです。
同着は〜、、、どうでしょうね。二つ一緒にくる、つまり後ろのに乗れば空いてる、とかそういう判断もありそうですので、まったく無駄な情報ではないと思います。。。

指摘しておいてあれですが、これは据え置きがいいかと思いますが、どうでしょうか？

**Comment by sassy** [comment]
@pankona 
例えば
20:26 (2)
みたいに２台と表示するとかですかねぇ。。。めんどくさいかな？

**Comment by pankona** [comment]
@sassy 
それも良さそうですね！めんどくさくは、、、ない、、、と思います。

ただ3台以上はおそらくないと思われるので、
`20:26*` とか、`20:26!` みたいに、ちょっと記号をつけて「1台ではない」の意にするのもありかな、と。見た目スマートになる。

他のアイデアとしてはオプション利用で、
- -u で同着を表示しない
- 逆に、同着はデフォルトで表示するようにしていて、--verbose で同着も表示されるようになる

といったオプション利用も考えましたが、一生使わないオプションになる気がするので微妙かと思いましたです。

ちなみにオプション関連では、この件とあんまり関係ないですが、
- -n [NUM] で NUMの数だけ表示する、とか便利かも。

**Comment by sassy** [comment]
@pankona 
わかりました。記号使うとかで対応します(優先度低で)
Pull Request大歓迎です。

-n オプションは考えてました。
よかったら別Issue立てていただけると。

**Comment by sassy** [comment]
resolve for #7 
thx @pankona
